name = "EDM4hep"
uuid = "eb32b910-dde9-4347-8fce-cd6be3498f0c"
version = "0.4.6"
authors = ["Pere Mato <pere.mato@cern.ch>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
EDM4hepPlotsExt = ["FHist", "Plots"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Accessors = "0.1"
Combinatorics = "1.0.3"
Corpuscles = "2"
FHist = "0.11"
Graphs = "1"
Preferences = "1.5.0"
PrettyTables = "2"
StaticArrays = "1.9"
StructArrays = "0.6"
UnROOT = "0.10"
YAML = "0.4"
julia = "1"
Plots = "1"
Statistics = "1"
RecipesBase = "1"