[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
EDM4hep = "eb32b910-dde9-4347-8fce-cd6be3498f0c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"
XRootD = "164e3b87-dc46-4cbc-97a6-5b310108fce0"
