[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EDM4hep = "eb32b910-dde9-4347-8fce-cd6be3498f0c"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LorentzVectorHEP = "f612022c-142a-473f-8cfd-a09cf3793c6c"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
